# Generated by Django 4.2 on 2024-09-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='cholesterol',
            field=models.FloatField(default=0.0, verbose_name='Cholesterol (mg)'),
        ),
        migrations.AddField(
            model_name='food',
            name='dietary_fibre',
            field=models.FloatField(default=0.0, verbose_name='Dietary Fibre (g)'),
        ),
        migrations.AddField(
            model_name='food',
            name='protein',
            field=models.FloatField(default=0.0, verbose_name='Protein (g)'),
        ),
        migrations.AddField(
            model_name='food',
            name='sodium',
            field=models.FloatField(default=0.0, verbose_name='Sodium (mg)'),
        ),
        migrations.AddField(
            model_name='food',
            name='sugar',
            field=models.FloatField(default=0.0, verbose_name='Sugar (g)'),
        ),
        migrations.AddField(
            model_name='food',
            name='total_carbohydrate',
            field=models.FloatField(default=0.0, verbose_name='Total Carbohydrate (g)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.FloatField(default=0.0, verbose_name='Calories (kcal)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='food',
            name='saturated_fat',
            field=models.FloatField(default=0.0, verbose_name='Saturated Fat (g)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='total_fat',
            field=models.FloatField(default=0.0, verbose_name='Total Fat (g)'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_time',
            field=models.IntegerField(choices=[(1, 'Breakfast'), (2, 'Morning Snack'), (3, 'Lunch'), (4, 'Afternoon Snack'), (5, 'Dinner'), (6, 'Evening Snack')], verbose_name='Meal Time'),
        ),
    ]
